# https://taskfile.dev

version: '3'

env:
  GOROOT:
    sh: go env GOROOT
  TINYGOROOT:
    sh: tinygo env TINYGOROOT || true

includes:
  go-wasm:
    taskfile: ./go-wasm/Taskfile.yml
    dir: ./go-wasm

tasks:
  build:
    cmds:
      - task: build:go
      - task: copy:wasm
      - task: build:ts

  copy:wasm:
    desc: 'Copy WASM and wasm_exec.js to TS project'
    cmds:
      - mkdir -p ts-lib/src/wasm
      - cp go-wasm/dist/wasm_exec.js ts-lib/src/wasm/wasm_exec.js
      - cp go-wasm/dist/tinyimg.wasm ts-lib/src/wasm/tinyimg.wasm

  build:go:
    desc: 'Build WASM binary and include wasm_exec.js'
    cmds:
      - task: go-wasm:build

  build:ts:
    desc: 'Build TypeScript library'
    dir: ts-lib
    cmds:
      - pnpm build
    deps: ['copy:wasm']

  clean:
    desc: Clean all build artifacts
    cmds:
      - task: clean:go
      - task: clean:ts

  clean:go:
    desc: 'Remove compiled WASM artifacts'
    dir: go-wasm
    cmds:
      - rm -rf dist

  clean:ts:
    desc: 'Remove TypeScript build artifacts'
    dir: ts-lib
    cmds:
      - rm -rf dist
